MODEL:
  TYPE: generalized_wsl
  CONV_BODY: VGG16.add_VGG16_conv5_body_origin
  NUM_CLASSES: 21
  MASK_ON: False
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MOMENTUM: 0.9
  #MAX_ITER: 35000
  #STEPS: [0, 35000]
  MAX_ITER: 200000
  STEPS: [0, 150000]
  WARM_UP_ITERS: 0
FAST_RCNN:
  ROI_BOX_HEAD: webly_heads.add_VGG16_roi_2fc_noise_head
  ROI_XFORM_METHOD: RoIPoolF
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: models/VGG/VGG_ILSVRC_16_layers_v1.pkl
  DATASETS: ('flickr_voc',)
  PROPOSAL_FILES: ('detectron/datasets/data/flickr_voc/mcg.pkl',)
  SCALES: (480, 576, 688, 864, 1200)
  MAX_SIZE: 2000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 2048
  FREEZE_CONV_BODY: True
  CROWD_FILTER_THRESH: 0.0
  SNAPSHOT_ITERS: 10000
TEST:
  DATASETS: ('voc_2007_test',)
  #DATASETS: ('voc_2012_test',)
  PROPOSAL_FILES: ('detectron/datasets/data/proposals/mcg_voc_2007_test.pkl',)
  #PROPOSAL_FILES: ('detectron/datasets/data/proposals/mcg_voc_2012_test.pkl',)
  PROPOSAL_LIMIT: 9999
  SCALE: 688
  MAX_SIZE: 4000
  NMS: 0.5
  BBOX_REG: False
  SCORE_THRESH: 0.000000001
  #DETECTIONS_PER_IM: 10000
  DETECTIONS_PER_IM: 100
  BBOX_AUG:
    ENABLED: False
    SCORE_HEUR: 'AVG'
    COORD_HEUR: 'ID'
    H_FLIP: True
    SCALES: (480, 576, 864, 1200)
    MAX_SIZE: 4000
    SCALE_H_FLIP: True
OUTPUT_DIR: .
RNG_SEED: 11
PIXEL_MEANS: [[[103.939, 116.779, 123.68]]]
WSL:
  WSL_ON: True
  ITER_SIZE: 1
  DEBUG: False
  SAMPLE: True
  SAMPLE_ITER: 1280
  DILATION: 2
  MEAN_LOSS: True
WEBLY:
  WEBLY_ON: True
  ENTROPY: True
  BAGGING_MIXUP: True
  BAGGING_MIXUP_ALPHA: 1.5
  MINING: False
MEMONGER: True
VIS: False
VIS_TH: 0.1
USE_NCCL: True
DEDUP_BOXES: 0.125
